package by.epam.university.controller.command.front;

public enum CommandName {
	SIGN_IN, REGISTRATION, NO_SUCH_COMMAND, CHANGE_LOCAL, SHOW_SPECIALTIES, SIGN_OUT, SHOW_USERPAGE,
	SHOW_ADDAPPLICATION_PAGE, ADD_APPLICATION, ADMIN_PAGE, ADD_SCHOOL, ADD_PRIVILEGE, ADD_FACULTY, ADD_TYPE_STUDY,
	ADD_SPECIALTY, SHOW_UPDATE_SPECIALTY_PAGE, SHOW_UPDATE_FACULTY_PAGE, SHOW_UPDATE_TYPE_STUDY_PAGE,
	SHOW_UPDATE_PRIVILEGE_PAGE, SHOW_UPDATE_SCHOOL_PAGE, UPDATE_SCHOOL, UPDATE_SPECIALTY, UPDATE_FACULTY,
	UPDATE_PRIVILEGE, UPDATE_TYPE_STUDY, SHOW_ADD_SPECIALTY_PAGE, SHOW_SPECIALTY_DETAIL, CONFIRM_ACCOUNT, ADD_SUBJECT,
	SHOW_UPDATE_SUBJECT_PAGE, UPDATE_SUBJECT, UPDATE_APPLICATION, APPLICATIONS_SPECIALTY, ACCEPT_STUDENT,
	REMOVE_SPECIALTY, REMOVE_SUBJECT, REMOVE_TYPE_STUDY, REMOVE_FACULTY, REMOVE_PRIVILEGE, REMOVE_SCHOOL;
}
